<template>
    <CsvGrid title="Adult Roles" :headers="this.headers" :rows="this.people" :defaultSortKeys="this.defSortKey"/>
</template>

<script setup>
import CsvGrid from '../components/CsvGrid.vue'
</script>

<script>
export default {
  data: () => ({
    defSortKey: "Last",
    headers: [
      { title: 'First', align: 'start', key: 'First' },
      { title: 'Last', align: 'start', key: 'Last' },
      //{ title: 'Role', align: 'start', key: 'Role' },
      { title: 'Position', align: 'start', key: 'Position' },
      { title: 'When', align: 'start', key: 'Date' },
      { title: 'Where', align: 'start', key: 'Location' },
      { title: 'Coordinator', align: 'start', key: 'Coordinator' },
      //{ title: 'Email', align: 'start', key: 'Email' },
    ],
    people:
      [
        {
          Last: "Arends-Kuenning",
          First: "Mary",
          Role: "Volunteer",
          Position: "Silent Auction",
          Assignment: "Volunteer - Silent Auction",
          Date: "Saturday 6:00 - 9:30 pm",
          Location: "Assembly Hall C",
          Coordinator: "Kim Balzer",
          Email: "arendskuenning@gmail.com"
        },
        {
          Last: "Ayers",
          First: "Gwyn",
          Role: "Coordinator",
          Position: "Filipino Program Liason",
          Assignment: "Coordinator - Filipino Program Liason",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "gwynayers@comcast.net"
        },
        {
          Last: "Balzer",
          First: "Jeremy",
          Role: "Volunteer",
          Position: "Lunch Clean Up",
          Assignment: "Volunteer - Lunch Clean Up",
          Date: "Friday 1:00 - 4:00 pm",
          Location: "Assembly Hall Porch",
          Coordinator: "Summer Popelka",
          Email: "Kim@balzerfamily.com"
        },
        {
          Last: "Balzer",
          First: "Kim",
          Role: "Coordinator",
          Position: "Silent Auction",
          Assignment: "Coordinator - Silent Auction",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "Kim@balzerfamily.com"
        },
        {
          Last: "Benzing",
          First: "Lynne",
          Role: "Coordinator",
          Position: "Market",
          Assignment: "Coordinator - Market",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "jillnation@hotmail.com"
        },
        {
          Last: "Biddulph",
          First: "Karen",
          Role: "Coordinator",
          Position: "Registration",
          Assignment: "Coordinator - Registration",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "kbiddulph1@yahoo.com"
        },
        {
          Last: "Bischoff",
          First: "Jill",
          Role: "Coordinator",
          Position: "Market",
          Assignment: "Coordinator - Market",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "jillnation@hotmail.com"
        },
        {
          Last: "Bischoff",
          First: "Todd",
          Role: "Coordintor",
          Position: "Photograpy/Slide Show",
          Assignment: "Coordintor - Photograpy/Slide Show",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "jillnation@hotmail.com"
        },
        {
          Last: "Brabham",
          First: "Chris",
          Role: "Volunteer",
          Position: "Gala and Cleanup",
          Assignment: "Volunteer - Gala and Cleanup",
          Date: "Saturday 6:45 - 10:00 pm",
          Location: "Assembly Hall C",
          Coordinator: "Mary Haber",
          Email: "Brabhamchris@gmail.com"
        },
        {
          Last: "Brabham",
          First: "Jo",
          Role: "Volunteer",
          Position: "Registration",
          Assignment: "Volunteer - Registration",
          Date: "Thursday 6:00 - 9:00 pm",
          Location: "Assembly Hall C",
          Coordinator: "Karen Biddulph",
          Email: "jobrabham@yahoo.com"
        },
        {
          Last: "Brooker",
          First: "Aaron",
          Role: "Volunteer",
          Position: "Middle School and Elementary Programming",
          Assignment: "Volunteer - Middle School and Elementary Programming",
          Date: "",
          Location: "",
          Coordinator: "Claire Brooker",
          Email: "aaronclaire2009@gmail.com"
        },
        {
          Last: "Brooker",
          First: "Claire",
          Role: "Coordinator",
          Position: "Middle School and Elementary Programming",
          Assignment: "Coordinator - Middle School and Elementary Programming",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "aaronclaire2009@gmail.com"
        },
        {
          Last: "Campbell",
          First: "Greg",
          Role: "Volunteer",
          Position: "Market Pack Up",
          Assignment: "Volunteer - Market Pack Up",
          Date: "Saturday 2:00 - 5:00 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "francampbell932735@gmail.com"
        },
        {
          Last: "Campbell",
          First: "Griffin",
          Role: "Volunteer",
          Position: "Market Pack Up",
          Assignment: "Volunteer - Market Pack Up",
          Date: "Saturday 2:00 - 5:00 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "francampbell932735@gmail.com"
        },
        {
          Last: "Case",
          First: "Jim",
          Role: "Volunteer",
          Position: "Cooking Workshop",
          Assignment: "Volunteer - Cooking Workshop",
          Date: "Friday 12:30 - 3:00 pm\nSaturday 10 am - noon",
          Location: "Everhart Cabin",
          Coordinator: "Gwyn Ayers",
          Email: "jimicase@comcast.net"
        },
        {
          Last: "Connolly",
          First: "Diane",
          Role: "Volunteer",
          Position: "Registration",
          Assignment: "Volunteer - Registration",
          Date: "Thursday 3:00 - 6:00 pm",
          Location: "Assembly Hall C",
          Coordinator: "Karen Biddulph",
          Email: "dianedmclaw@comcast.net"
        },
        {
          Last: "Decker",
          First: "Julie",
          Role: "Volunteer",
          Position: "BBQ",
          Assignment: "Volunteer - BBQ",
          Date: "Thursday 3:30 - 6:30 pm",
          Location: "Assembly Hall Porch",
          Coordinator: "Phil Reu",
          Email: "juliebdecker@gmail.com"
        },
        {
          Last: "Delany",
          First: "Jan",
          Role: "Volunteer",
          Position: "High School Event Driver & Songkran",
          Assignment: "High School Event Driver & Songkran",
          Date: "Friday 8:45 - 10:30 am, Friday 3:00 - 4:30 pm, Saturday 3:00 - 4:00 pm",
          Location: "Assembly Hall to Estes Park High, Jacques' Place",
          Coordinator: "Charlotte Magee, Kyle Henderson",
          Email: "karin.delany@heritagecamps.org"
        },
        {
          Last: "Delany",
          First: "Karin",
          Role: "Director, Coordinator",
          Position: "Thai Program Liaison",
          Assignment: "Director, Coordinator - Thai Program Liaison",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "karin.delany@heritagecamps.org"
        },
        {
          Last: "Dixon",
          First: "Ella",
          Role: "Volunteer",
          Position: "Gala Setup",
          Assignment: "Volunteer - Gala Setup",
          Date: "Saturday 1:30 - 4:30 pm",
          Location: "Assembly Hall C",
          Coordinator: "Mary Haber",
          Email: "laurenahaag@eaton.com"
        },
        {
          Last: "Donahue",
          First: "Trish",
          Role: "Volunteer",
          Position: "Counselor Meals",
          Assignment: "Volunteer - Counselor Meals",
          Date: "Friday 4:00 - 6:30 pm",
          Location: "Everhart Cabin",
          Coordinator: "Kari Gillenwater",
          Email: "taostrish@yahoo.com"
        },
        {
          Last: "Doubleday",
          First: "Kelly",
          Role: "Volunteer",
          Position: "Gala Food Run & Setup",
          Assignment: "Volunteer - Gala Food Run & Setup",
          Date: "Saturday 1:30 - 4:30 pm",
          Location: "Assembly Hall C",
          Coordinator: "Mary Haber",
          Email: "doubledayk104@gmail.com"
        },
        {
          Last: "Ebel",
          First: "Karl",
          Role: "Volunteer",
          Position: "BBQ",
          Assignment: "Volunteer - BBQ",
          Date: "Thursday 3:30 - 6:30 pm",
          Location: "Assembly Hall Porch",
          Coordinator: "Phil Reu",
          Email: "kelli.innerworks@gmail.com"
        },
        {
          Last: "Ebel",
          First: "Kelli",
          Role: "Volunteer",
          Position: "BBQ",
          Assignment: "Volunteer - BBQ",
          Date: "Thursday 3:30 - 6:30 pm",
          Location: "Assembly Hall Porch",
          Coordinator: "Phil Reu",
          Email: "kelli.innerworks@gmail.com"
        },
        {
          Last: "Edwards",
          First: "Caitlin",
          Role: "Volunteer",
          Position: "Silent Auction",
          Assignment: "Volunteer - Silent Auction",
          Date: "Saturday 6:00 - 9:30 pm",
          Location: "Assembly Hall C",
          Coordinator: "Kim Balzer",
          Email: "caitlincedwards@gmail.com"
        },
        {
          Last: "Edwards",
          First: "Clayton",
          Role: "Volunteer",
          Position: "Lunch Prep",
          Assignment: "Volunteer - Lunch Prep",
          Date: "Saturday 9:00 am - 12:30 pm",
          Location: "Dannen Cabin",
          Coordinator: "Summer Popelka",
          Email: "caitlincedwards@gmail.com"
        },
        {
          Last: "Everett",
          First: "Christen",
          Role: "Coordinator",
          Position: "Lunch",
          Assignment: "Coordinator - Lunch",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "ceverett@ga.essd40.com"
        },
        {
          Last: "Everett",
          First: "Victor",
          Role: "Coordinator",
          Position: "Lunch",
          Assignment: "Coordinator - Lunch",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "vic63750@gmail.com"
        },
        {
          Last: "George",
          First: "Alison",
          Role: "Coordinator",
          Position: "Ice Cream Social",
          Assignment: "Coordinator - Ice Cream Social",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "Alisongeorge2010@gmail.com"
        },
        {
          Last: "Gillenwater",
          First: "Kari",
          Role: "Coordinator",
          Position: "Counselor Meals",
          Assignment: "Coordinator - Counselor Meals",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "kari_gillenwater@yahoo.com"
        },
        {
          Last: "Gray",
          First: "Kathryn",
          Role: "Volunteer",
          Position: "Lunch Prep",
          Assignment: "Volunteer - Lunch Prep",
          Date: "Friday 9:00 am - 12:30 pm",
          Location: "Dannen Cabin",
          Coordinator: "Summer Popelka",
          Email: "kelindsey@gmail.com"
        },
        {
          Last: "Gray IV",
          First: "Robert",
          Role: "Volunteer",
          Position: "Photography",
          Assignment: "Volunteer - Photography",
          Date: "Saturday 8:15 am - 12:15pm",
          Location: "",
          Coordinator: "Todd Bischoff",
          Email: "bluewaterrobby@gmail.com"
        },
        {
          Last: "Haag",
          First: "Lauren",
          Role: "Coordinator",
          Position: "Opening and Closing",
          Assignment: "Coordinator - Opening and Closing",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "laurenahaag@eaton.com"
        },
        {
          Last: "Haag",
          First: "Matt",
          Role: "Coordinator",
          Position: "Lunch",
          Assignment: "Coordinator - Lunch",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "matt.haag@comcast.net"
        },
        {
          Last: "Haber",
          First: "Mary",
          Role: "Coordinator",
          Position: "Gala",
          Assignment: "Coordinator - Gala",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "mary_haber@yahoo.com"
        },
        {
          Last: "Hammond",
          First: "Alicia",
          Role: "Volunteer",
          Position: "Gala Beverages",
          Assignment: "Volunteer - Gala Beverages",
          Date: "Saturday 6:45 - 10:00 pm",
          Location: "Assembly Hall C",
          Coordinator: "Mary Haber",
          Email: "alicia_hammond@cate.org"
        },
        {
          Last: "Hammond",
          First: "Ron",
          Role: "Volunteer",
          Position: "Gala Beverages",
          Assignment: "Volunteer - Gala Beverages",
          Date: "Saturday 6:45 - 10:00 pm",
          Location: "Assembly Hall C",
          Coordinator: "Mary Haber",
          Email: "alicia_hammond@cate.org"
        },
        {
          Last: "Harwell",
          First: "Michelle",
          Role: "Parent Presenter",
          Position: "Parent Presenter",
          Assignment: "Parent Presenter",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "mharwelltherapy@gmail.com"
        },
        {
          Last: "Hayes",
          First: "Kelly",
          Role: "Volunteer",
          Position: "Market Cashier",
          Assignment: "Volunteer - Market Cashier",
          Date: "Friday 6:00 - 8:30 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "Kellyhayes02@yahoo.com"
        },
        {
          Last: "Henderson",
          First: "Amanda",
          Role: "Parent Presenter",
          Position: "Parent Presenter",
          Assignment: "Parent Presenter",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "amanda2440@gmail.com"
        },
        {
          Last: "Henderson",
          First: "Chasen",
          Role: "Volunteer",
          Position: "Presenters' Reception",
          Assignment: "Volunteer - Presenters' Reception",
          Date: "Friday 4:00 - 7:00 pm",
          Location: "Dannen Cabin",
          Coordinator: "Karen Melusky",
          Email: "kristalmelusky@gmail.com"
        },
        {
          Last: "Henderson",
          First: "Kyle",
          Role: "Coordinator",
          Position: "Songkran\nVolunteer - High School Event Driver",
          Assignment: "Coordinator - Songkran\nVolunteer - High School Event Driver",
          Date: "Friday 8:45 - 10:30 am\nFriday 3:00 - 4:30 pm",
          Location: "Assembly Hall to Estes Park High",
          Coordinator: "Charlotte Magee",
          Email: "kylejhenderson@msn.com"
        },
        {
          Last: "Hoffman",
          First: "Jonathan",
          Role: "Volunteer",
          Position: "Counselor Meals",
          Assignment: "Volunteer - Counselor Meals",
          Date: "Saturday 4:00 - 6:30 pm",
          Location: "Everhart Cabin",
          Coordinator: "Kari Gillenwater",
          Email: "shelterdog48@gmail.com"
        },
        {
          Last: "Hoffman",
          First: "Susan",
          Role: "Volunteer",
          Position: "Lunch Prep",
          Assignment: "Volunteer - Lunch Prep",
          Date: "Friday 9:00 am - 12:30 pm",
          Location: "Dannen Cabin",
          Coordinator: "Summer Popelka",
          Email: "susanehoffman1@icloud.com"
        },
        {
          Last: "Jensen",
          First: "Heidi",
          Role: "Volunteer",
          Position: "Market Cashier",
          Assignment: "Volunteer - Market Cashier",
          Date: "Sat 8:00 - 9:00 am & noon - 1:30 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "hjensenlee@gmail.com"
        },
        {
          Last: "Johnson",
          First: "Al",
          Role: "Volunteer",
          Position: "Presenters' Reception",
          Assignment: "Volunteer - Presenters' Reception",
          Date: "Friday 3:00 - 6:00 pm",
          Location: "Dannen Cabin",
          Coordinator: "Karen Melusky",
          Email: "liz.twombly@gmail.com"
        },
        {
          Last: "Johnson",
          First: "Kay",
          Role: "Volunteer",
          Position: "Presenters' Reception",
          Assignment: "Volunteer - Presenters' Reception",
          Date: "Friday 3:00 - 6:00 pm",
          Location: "Dannen Cabin",
          Coordinator: "Karen Melusky",
          Email: "liz.twombly@gmail.com"
        },
        {
          Last: "Johnson",
          First: "Steven",
          Role: "Volunteer",
          Position: "Market Pack Up",
          Assignment: "Volunteer - Market Pack Up",
          Date: "Saturday 2:00 - 5:00 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "taryn.f.johnson@gmail.com"
        },
        {
          Last: "Kremer",
          First: "Kristi",
          Role: "Coordinator",
          Position: "Vietnamese Program",
          Assignment: "Coordinator - Vietnamese Program",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: ""
        },
        {
          Last: "Kremer",
          First: "Mark",
          Role: "Coordinator",
          Position: "Vietnamese Program",
          Assignment: "Coordinator - Vietnamese Program",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: ""
        },
        {
          Last: "Kuenning",
          First: "Josie",
          Role: "Volunteer",
          Position: "Market Setup",
          Assignment: "Volunteer - Market Setup",
          Date: "Thursday 1:00 - 4:00 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "mkuenning@hotmail.com"
        },
        {
          Last: "Kuenning",
          First: "Matt",
          Role: "Director",
          Position: "Director",
          Assignment: "Director",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "mkuenning@hotmail.com"
        },
        {
          Last: "Langefels",
          First: "DJ",
          Role: "Volunteer",
          Position: "Lunch Prep",
          Assignment: "Volunteer - Lunch Prep",
          Date: "Saturday 9:00 am - 12:30 pm",
          Location: "Dannen Cabin",
          Coordinator: "Summer Popelka",
          Email: "djlangefels@gmail.com"
        },
        {
          Last: "Langefels",
          First: "Rachel",
          Role: "Volunteer",
          Position: "Lunch Prep",
          Assignment: "Volunteer - Lunch Prep",
          Date: "Saturday 9:00 am - 12:30 pm",
          Location: "Dannen Cabin",
          Coordinator: "Summer Popelka",
          Email: "rachelle.621@gmail.com"
        },
        {
          Last: "Lee",
          First: "Kevin",
          Role: "Volunteer",
          Position: "Lunch Clean Up",
          Assignment: "Volunteer - Lunch Clean Up",
          Date: "Saturday 1:00 - 4:00 pm",
          Location: "Assembly Hall Porch",
          Coordinator: "Summer Popelka",
          Email: "kjensenlee@gmail.com"
        },
        {
          Last: "Magee",
          First: "Charlotte",
          Role: "Coordinator",
          Position: "High School Program",
          Assignment: "Coordinator - High School Program",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "mageecharlotte@gmail.com"
        },
        {
          Last: "Magee",
          First: "Todd",
          Role: "Volunteer",
          Position: "High School Event Driver",
          Assignment: "Volunteer - High School Event Driver",
          Date: "Friday 8:45 - 10:30 am\nFriday 3:00 - 4:30 pm",
          Location: "Assembly Hall to Estes Park High",
          Coordinator: "Charlotte Magee",
          Email: "mageecharlotte@gmail.com"
        },
        {
          Last: "Maryn",
          First: "Rich",
          Role: "Volunteer",
          Position: "Truck Unloading\nVolunteer - Market Setup",
          Assignment: "Volunteer - Truck Unloading\nVolunteer - Market Setup",
          Date: "Thursday 12:00 - 3:00 pm",
          Location: "Assembly Hall Loading Dock",
          Coordinator: "Eric Voogt \nJill Bischoff",
          Email: "juliebdecker@gmail.com"
        },
        {
          Last: "May",
          First: "Robert",
          Role: "Coordinator",
          Position: "Parent Social",
          Assignment: "Coordinator - Parent Social",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "Bmay@wafb.com"
        },
        {
          Last: "May",
          First: "Sandra",
          Role: "Volunteer",
          Position: "Parent Social",
          Assignment: "Volunteer - Parent Social",
          Date: "",
          Location: "",
          Coordinator: "Bob May",
          Email: "Smayrd@cox.net"
        },
        {
          Last: "McClay",
          First: "Natasha",
          Role: "Coordinator",
          Position: "Silent Auction",
          Assignment: "Coordinator - Silent Auction",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "natmcclay@hotmail.com"
        },
        {
          Last: "McClay",
          First: "Robert",
          Role: "Volunteer",
          Position: "Lunch Clean Up",
          Assignment: "Volunteer - Lunch Clean Up",
          Date: "Friday 1:00 - 4:00 pm",
          Location: "Assembly Hall Porch",
          Coordinator: "Summer Popelka",
          Email: "natmcclay@hotmail.com"
        },
        {
          Last: "McVicker",
          First: "Melissa",
          Role: "Volunteer",
          Position: "Registration",
          Assignment: "Volunteer - Registration",
          Date: "Thursday 3:00 - 6:00 pm",
          Location: "Assembly Hall C",
          Coordinator: "Karen Biddulph",
          Email: "melmcv@gmail.com"
        },
        {
          Last: "Meddaugh",
          First: "Lynne",
          Role: "Volunteer",
          Position: "Lunch Prep",
          Assignment: "Volunteer - Lunch Prep",
          Date: "Friday 9:00 am - 12:30 pm",
          Location: "Dannen Cabin",
          Coordinator: "Summer Popelka",
          Email: "lmeddaugh@gmail.com"
        },
        {
          Last: "Melusky",
          First: "Karen",
          Role: "Coordinator",
          Position: "Presenters' Reception",
          Assignment: "Coordinator - Presenters' Reception",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "karenmelusky@yahoo.com"
        },
        {
          Last: "Melusky",
          First: "Mike",
          Role: "Coordinator",
          Position: "Presenters' Reception",
          Assignment: "Coordinator - Presenters' Reception",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "karenmelusky@yahoo.com"
        },
        {
          Last: "Miller",
          First: "Anne",
          Role: "Volunteer",
          Position: "Lunch Clean Up",
          Assignment: "Volunteer - Lunch Clean Up",
          Date: "Saturday 1:00 - 4:00 pm",
          Location: "Assembly Hall Porch",
          Coordinator: "Summer Popelka",
          Email: "anne.chamisa@gmail.com"
        },
        {
          Last: "Miller-Francisco",
          First: "Emily",
          Role: "Volunteer",
          Position: "Coffee Cart",
          Assignment: "Volunteer - Coffee Cart",
          Date: "Friday 12:15 - 4:00 pm",
          Location: "Assembly Hall",
          Coordinator: "Aryn Sloan",
          Email: "emillfran@msn.com"
        },
        {
          Last: "Patel",
          First: "Kushang",
          Role: "Coordinator",
          Position: "Counselor Meals",
          Assignment: "Coordinator - Counselor Meals",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "kari_gillenwater@yahoo.com"
        },
        {
          Last: "Polk",
          First: "Rebecca",
          Role: "Volunteer",
          Position: "Photography",
          Assignment: "Volunteer - Photography",
          Date: "Friday 8:15 am - 12:15pm",
          Location: "",
          Coordinator: "Todd Bischoff",
          Email: "ptverus@gmail.com"
        },
        {
          Last: "Popelka",
          First: "Michael",
          Role: "Coordinator",
          Position: "Lunch",
          Assignment: "Coordinator - Lunch",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "smpopelka@gmail.com"
        },
        {
          Last: "Popelka",
          First: "Summer",
          Role: "Coordinator",
          Position: "Lunch",
          Assignment: "Coordinator - Lunch",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "smpopelka@gmail.com"
        },
        {
          Last: "Reu",
          First: "Laura",
          Role: "Volunteer",
          Position: "BBQ",
          Assignment: "Volunteer - BBQ",
          Date: "Thursday 3:30 - 6:30 pm",
          Location: "Assembly Hall Porch",
          Coordinator: "Phil Reu",
          Email: "phillip.reu@gmail.com"
        },
        {
          Last: "Reu",
          First: "Phillip",
          Role: "Coordinator",
          Position: "BBQ",
          Assignment: "Coordinator - BBQ",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "phillip.reu@gmail.com"
        },
        {
          Last: "Schenck",
          First: "Kim",
          Role: "Volunteer",
          Position: "Coffee Cart",
          Assignment: "Volunteer - Coffee Cart",
          Date: "Saturday 8:15 am - 12:15 pm",
          Location: "Assembly Hall",
          Coordinator: "Aryn Sloan",
          Email: "Kim.Schenck@gmail.com"
        },
        {
          Last: "Sloan",
          First: "Aryn",
          Role: "Coordinator",
          Position: "Coffee Cart",
          Assignment: "Coordinator - Coffee Cart",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "sloan_family@comcast.net"
        },
        {
          Last: "Sloan",
          First: "Scott",
          Role: "Coordinator",
          Position: "Coffee Cart",
          Assignment: "Coordinator - Coffee Cart",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "sloan_family@comcast.net"
        },
        {
          Last: "Spears",
          First: "Charles",
          Role: "Volunteer",
          Position: "Gala and Cleanup",
          Assignment: "Volunteer - Gala and Cleanup",
          Date: "Saturday 6:45 - 10:00 pm",
          Location: "Assembly Hall C",
          Coordinator: "Mary Haber",
          Email: "egonio.vivian@gmail.com"
        },
        {
          Last: "Steinert",
          First: "David",
          Role: "Volunteer",
          Position: "Coffee Cart",
          Assignment: "Volunteer - Coffee Cart",
          Date: "Saturday 12:15 - 4:00 pm",
          Location: "Assembly Hall",
          Coordinator: "Aryn Sloan",
          Email: "Kim.Schenck@gmail.com"
        },
        {
          Last: "Strand",
          First: "Laura",
          Role: "Volunteer",
          Position: "Market Cashier",
          Assignment: "Volunteer - Market Cashier",
          Date: "Friday 6:00 - 8:30 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "lstrand32@gmail.com"
        },
        {
          Last: "Surwillo",
          First: "Afton",
          Role: "Volunteer",
          Position: "Market Cashier",
          Assignment: "Volunteer - Market Cashier",
          Date: "Fri 8:00 - 9:00 am & noon - 1:30 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "afton68@gmail.com"
        },
        {
          Last: "Surwillo",
          First: "Steve",
          Role: "Volunteer",
          Position: "Market Cashier",
          Assignment: "Volunteer - Market Cashier",
          Date: "Fri 8:00 - 9:00 am & noon - 1:30 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "steve.surwillo@gmail.com"
        },
        {
          Last: "Thomas",
          First: "Brandi",
          Role: "Volunteer",
          Position: "Coffee Cart",
          Assignment: "Volunteer - Coffee Cart",
          Date: "Friday 8:15 am - 12:15 pm",
          Location: "Assembly Hall",
          Coordinator: "Aryn Sloan",
          Email: "brandimthomas@msn.com"
        },
        {
          Last: "Thomas",
          First: "Mike",
          Role: "Volunteer",
          Position: "Ice Cream Social",
          Assignment: "Volunteer - Ice Cream Social",
          Date: "Friday 6:30 - 9:00 pm",
          Location: "Assembly Hall Porch",
          Coordinator: "Allison George",
          Email: "brandimthomas@msn.com"
        },
        {
          Last: "Thompson",
          First: "Elizabeth",
          Role: "Volunteer",
          Position: "Market Setup",
          Assignment: "Volunteer - Market Setup",
          Date: "Thursday 1:00 - 4:00 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "elizabethmeihu@gmail.com"
        },
        {
          Last: "Thompson",
          First: "Robert",
          Role: "Coordinator",
          Position: "A/V Support",
          Assignment: "Coordinator - A/V Support",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "roberttco@gmail.com"
        },
        {
          Last: "Thompson",
          First: "Stephanie",
          Role: "Coordinator",
          Position: "High School Program",
          Assignment: "Coordinator - High School Program",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "stephthompson28@gmail.com"
        },
        {
          Last: "Thompson",
          First: "Veronica",
          Role: "Director",
          Position: "Director",
          Assignment: "Director",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "veronicalynnthompson@gmail.com"
        },
        {
          Last: "Toukan",
          First: "Linda",
          Role: "Volunteer",
          Position: "Market Cashier",
          Assignment: "Volunteer - Market Cashier",
          Date: "Sat 8:00 - 9:00 am & noon - 1:30 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "LindaToukan@comcast.net"
        },
        {
          Last: "Toukan",
          First: "Mark",
          Role: "Coordinator",
          Position: "Autograph books\nCoordinator - New families\nVolunteer - Market Cashier",
          Assignment: "Coordinator - Autograph books\nCoordinator - New families\nVolunteer - Market Cashier",
          Date: "Thurs 6:00 - 7:00 & 8:00 - 9:00 pm",
          Location: "Assembly Hall B",
          Coordinator: "Jill Bischoff",
          Email: "m.toukan@comcast.net"
        },
        {
          Last: "Twombly",
          First: "Elizabeth",
          Role: "Coordinator",
          Position: "Childcare/PreSchool",
          Assignment: "Coordinator - Childcare/PreSchool",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "liz.twombly@gmail.com"
        },
        {
          Last: "Voogt",
          First: "Eric",
          Role: "Coordinator",
          Position: "Truck Driver",
          Assignment: "Coordinator - Truck Driver",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "evoogt@inmanflynn.com"
        },
        {
          Last: "West",
          First: "Paul",
          Role: "Coordinator",
          Position: "Registration",
          Assignment: "Coordinator - Registration",
          Date: "",
          Location: "",
          Coordinator: "",
          Email: "paul.west@mastersny.org"
        },
        {
          Last: "Whitefield",
          First: "Zoe",
          Role: "Volunteer",
          Position: "Gala and Cleanup",
          Assignment: "Volunteer - Gala and Cleanup",
          Date: "Saturday 6:45 - 10:00 pm",
          Location: "Assembly Hall C",
          Coordinator: "Mary Haber",
          Email: "egonio.vivian@gmail.com"
        }
      ]
  })
}
</script>
